
package practico5.igu;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.internal.org.objectweb.asm.commons.StaticInitMerger;

/**
 *
 * @author marus
 */
public class IngresarDatos extends javax.swing.JFrame {
    private DefaultTableModel modelo = new DefaultTableModel();

    /**
     * Creates new form IngresarDatos
     */
    public IngresarDatos() {
        initComponents();
        confeccion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTitulo2 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtInventario = new javax.swing.JTable();
        jlCodigo = new javax.swing.JLabel();
        jtfNumeroCodigo = new javax.swing.JTextField();
        jlProducto = new javax.swing.JLabel();
        jtfProducto = new javax.swing.JTextField();
        jlPrecio = new javax.swing.JLabel();
        jtfPrecio = new javax.swing.JTextField();
        jlStock = new javax.swing.JLabel();
        jsNumeroStock = new javax.swing.JSpinner();
        jbAgregarProducto = new javax.swing.JButton();
        jbBorrar = new javax.swing.JButton();
        jbFinalizarCarga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 243, 237));
        jPanel1.setForeground(new java.awt.Color(204, 233, 220));

        jlTitulo2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlTitulo2.setText("              INGRESO DE MERCADERIA");
        jlTitulo2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jcbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALIMENTOS", "ARTICULOS VARIOS", "ROPA", "VACUNAS", " ", " " }));
        jcbCategoria.setSelectedIndex(-1);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Categoria:");

        jtInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COD", "PRODUCTO", "CATEGORIA", "PRECIO", "STOCK"
            }
        ));
        jScrollPane1.setViewportView(jtInventario);

        jlCodigo.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlCodigo.setText("COD:  ");

        jtfNumeroCodigo.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlProducto.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlProducto.setText("Producto : ");

        jtfProducto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlPrecio.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlPrecio.setText("Precio : ");

        jtfPrecio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlStock.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jlStock.setText("Stock : ");

        jsNumeroStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jbAgregarProducto.setText("Agregar Producto");
        jbAgregarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarProductoActionPerformed(evt);
            }
        });

        jbBorrar.setText("Borrar");
        jbBorrar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBorrarActionPerformed(evt);
            }
        });

        jbFinalizarCarga.setText("Finalizar");
        jbFinalizarCarga.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbFinalizarCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFinalizarCargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlCodigo)
                                .addGap(29, 29, 29)
                                .addComponent(jtfNumeroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jlPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlProducto)
                                    .addComponent(jlStock))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jtfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jsNumeroStock, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jlTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jbAgregarProducto)
                .addGap(156, 156, 156)
                .addComponent(jbBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFinalizarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNumeroCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlProducto)
                    .addComponent(jtfProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCodigo)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPrecio)
                    .addComponent(jtfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStock)
                    .addComponent(jsNumeroStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAgregarProducto)
                    .addComponent(jbBorrar)
                    .addComponent(jbFinalizarCarga))
                .addGap(49, 49, 49)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbFinalizarCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFinalizarCargaActionPerformed
        Principal salida = new Principal();
        salida.setVisible(true);
        
    }//GEN-LAST:event_jbFinalizarCargaActionPerformed

    private void jbAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarProductoActionPerformed
        int COD = Integer.parseInt(jtfNumeroCodigo.getText());
        String producto = jtfProducto.getText();
        String categoria = (String)jcbCategoria.getSelectedItem();
        double precio =0;
        int stock =((Integer)jsNumeroStock.getValue());
        //creamos excepciones para el momento de carga de textos que sean correctos
        try {
            precio=Double.parseDouble(jtfPrecio.getText());
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(this,"Error ingrese un numero valido");
            return;
        }
        if ((!producto.equals("")&&(precio>0)&&(COD>0))) {
            Object arr[]={COD,producto,categoria,precio,stock};
             modelo.addRow(arr);
            
        } else {
            JOptionPane.showMessageDialog(this,"Error debe ingresar un dato");
        }
        //limpiamos los campos de textos;
        jtfNumeroCodigo.setText("");
        jtfProducto.setText("");
        jtfPrecio.setText("");
        jsNumeroStock.setValue("");
           
    }//GEN-LAST:event_jbAgregarProductoActionPerformed

    private void jbBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBorrarActionPerformed
       
        modelo.removeRow(modelo.getRowCount() - 1); //eliminamos una por una las celdas
    }//GEN-LAST:event_jbBorrarActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresarDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbAgregarProducto;
    private javax.swing.JButton jbBorrar;
    private javax.swing.JButton jbFinalizarCarga;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlPrecio;
    private javax.swing.JLabel jlProducto;
    private javax.swing.JLabel jlStock;
    private javax.swing.JLabel jlTitulo2;
    private javax.swing.JSpinner jsNumeroStock;
    private javax.swing.JTable jtInventario;
    private javax.swing.JTextField jtfNumeroCodigo;
    private javax.swing.JTextField jtfPrecio;
    private javax.swing.JTextField jtfProducto;
    // End of variables declaration//GEN-END:variables

    private void confeccion(){
        modelo.addColumn("COD");
        modelo.addColumn("PRODUCTO");
        modelo.addColumn("CATEGORIA");
        modelo.addColumn("PRECIO");
        modelo.addColumn("STOCK");
        jtInventario.setModel(modelo);
        
    }

}

